version: '3'

services:
  app:
    build: ./app
    container_name: teracom_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=PASSWORD_CHANGE_ME
      - POSTGRES_URL=jdbc:postgresql://db:5432/tera_db

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "15432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./init/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=PASSWORD_CHANGE_ME
      - POSTGRES_DB=tera_db


volumes:
  db-store: